const productInfo = [
	{
		id: 1,
		productName: "Inteligencia emocional y psicolgía positiva",
		price: 50,
		category: "seminario",
		img: "./img/psicologia_positiva.jpg",
		duration: "2 meses",
		modality: "online en vivo",
	},
	{
		id: 2,
		productName: "Los ciclos vitales y el desarrollo de la psiquis",
		price: 80,
		category: "especializacion",
		img: "./img/ciclos_vitales.jpg",
		duration: "5 meses",
		modality: "semi presencial",
	},
	{
		id: 3,
		productName: "Coaching para la administración del tiempo",
		price: 30,
		category: "curso",
		img: "./img/administracion_tiempo.jpg",
		duration: "8 clases",
		modality: "online ondemand",
	},
	{
		id: 4,
		productName: "Creatividad como cualidad básica",
		price: 60,
		category: "seminario",
		img: "./img/creatividad.jpg",
		duration: "3 meses",
		modality: "online en vivo",
	},
	{
		id: 5,
		productName: "Finanzas personales para la nueva era",
		price: 50,
		category: "seminario",

		img: "./img/finanzas.jpg",
		duration: "2 meses",
		modality: "online en vivo",
	},
	{
		id: 6,
		productName: "El viaje del Héroe; desarrollo personal",
		price: 50,
		category: "seminario",
		img: "./img/viaje.jpg",
		duration: "2 meses",
		modality: "online en vivo",
	},
	{
		id: 7,
		productName: "Master Class; Conversar y no morir en el intento",
		price: 25,
		category: "curso",
		img: "./img/masterclass.jpg",
		duration: "1 clase",
		modality: "online ondemand",
	},
	{
		id: 8,
		productName: "Mini curso de objetivos y organización",
		price: 40,
		category: "Curso",
		img: "./img/objetivos.jpg",
		duration: "4 clase",
		modality: "online ondemand",
	},
	{
		id: 9,
		productName: "Prácticas profecionales de Coaching",
		price: 100,
		category: "servicio",
		img: "./img/practicas.jpg",
		duration: "4 encuentros de 2 hs",
		modality: "online en vivo",
	},
	{
		id: 10,
		productName: "Sesión de coaching individual",
		price: 25,
		category: "servicio",
		img: "./img/sesion.jpg",
		duration: "1 encuentro de 1 hs",
		modality: "online en vivo",
	},
	{
		id: 11,
		productName: "Pack de sesiones mensual",
		price: 70,
		category: "servicio",
		img: "./img/pack_sesiones.jpg",
		duration: "4 encuentro de 1 hs",
		modality: "online en vivo",
	},
];
export { productInfo };
